language: node_js
cache:
  directories:
  - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: heroku
  edge: true,
  skip_cleanup: true
  api_key:
    secure: "$HEROKU_TOKEN"
  local-dir: dist/
  target-branch: deployment
  app: rickandmortyspa
  on:
    branch: master