language: node_js
cache:
  directories:
  - "~/.npm"
node_js:
  - '12'
git:
  depth: 3
scripts:
  - yarn build
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: rickandmortyspa
  on:
    branch: master
