language: node_js
cache:
  directories:
  - "~/.npm"
node_js:
- '12'
git:
  depth: 3
script:
- yarn build
deploy:
  provider: heroku
  edge: true
  skip_cleanup: true
  keep-history: true
  api_key:
    secure: "$HEROKU_TOKEN"
  local-dir: dist-
  app: rickandmortyspa
  target-brach: deployment
  commit_message: "Deploy Release"
  on:
    branch: master