language: node_js
cache: 
  directories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: heroku
  edge: true
  skip_cleanup: true
  keep_history: true
  api_key:
    secure: $HEROKU_TOKEN
  local-dir: dist/
  target_branch: master
  commit_message: 'Deploy Release'
  on:
    branch: master